### ISSUE TITLE
Artemis Crashes after enabling windows effect on g910

### ISSUE THREAD

**Issue by danii359** [SpoinkyNL/Artemis#101]
hi when i try to activate the windows effect on my G910 Artemis completely crashes with code errors.
i have screenshots to
![2016-06-09_23-49-22](https://cloud.githubusercontent.com/assets/8000741/15954455/e833138c-2e9c-11e6-989d-cdc19750dff8.png)
![2016-06-09_23-49-16](https://cloud.githubusercontent.com/assets/8000741/15954457/ecae5a8e-2e9c-11e6-9ddf-ddeb73d0e98a.png)

**Comment by SpoinkyNL** [comment]
Hello, could you click on Copy all to keyboard and paste the results here
on GitHub, in a code block preferably
Op 10 jun. 2016 6:50 a.m. schreef "danii359" <notifications@github.com>:

**Comment by danii359** [comment]
sure


`An unexpected error occurred in Artemis.

Exception has been thrown by the target of an invocation.

Cannot load Counter Name data because an invalid index '' was read from the registry.
____________________________________________________
System.Reflection.TargetInvocationException

Message:
Exception has been thrown by the target of an invocation.

Stack Trace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Caliburn.Micro.ActionMessage.<>c.<.cctor>b__33_0(ActionExecutionContext context)
   at Caliburn.Micro.ActionMessage.Invoke(Object eventArgs)
   at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

Source:
mscorlib

HResult:
-2146232828
____________________________________________________
System.InvalidOperationException

Message:
Cannot load Counter Name data because an invalid index '' was read from the registry.

Stack Trace:
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName)
   at Artemis.Modules.Effects.WindowsProfile.WindowsProfileModel.GetPerformanceCounters()
   at Artemis.Modules.Effects.WindowsProfile.WindowsProfileModel.SetupCpu()
   at Artemis.Modules.Effects.WindowsProfile.WindowsProfileModel.Enable()
   at Artemis.Managers.EffectManager.ChangeEffect(EffectModel effectModel, LoopManager loopManager)
   at Artemis.ViewModels.Abstract.EffectViewModel.ToggleEffect()

TargetSite:
System.Collections.Hashtable GetStringTable(Boolean)

Source:
System

HResult:
-2146233079
`

**Comment by danii359** [comment]
```
An unexpected error occurred in Artemis.

Exception has been thrown by the target of an invocation.

Cannot load Counter Name data because an invalid index '' was read from the registry.
____________________________________________________
System.Reflection.TargetInvocationException

Message:
Exception has been thrown by the target of an invocation.

Stack Trace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Caliburn.Micro.ActionMessage.<>c.<.cctor>b__33_0(ActionExecutionContext context)
   at Caliburn.Micro.ActionMessage.Invoke(Object eventArgs)
   at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

Source:
mscorlib

HResult:
-2146232828
____________________________________________________
System.InvalidOperationException

Message:
Cannot load Counter Name data because an invalid index '' was read from the registry.

Stack Trace:
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName)
   at Artemis.Modules.Effects.WindowsProfile.WindowsProfileModel.GetPerformanceCounters()
   at Artemis.Modules.Effects.WindowsProfile.WindowsProfileModel.SetupCpu()
   at Artemis.Modules.Effects.WindowsProfile.WindowsProfileModel.Enable()
   at Artemis.Managers.EffectManager.ChangeEffect(EffectModel effectModel, LoopManager loopManager)
   at Artemis.ViewModels.Abstract.EffectViewModel.ToggleEffect()

TargetSite:
System.Collections.Hashtable GetStringTable(Boolean)

Source:
System

HResult:
-2146233079
```

**Comment by SpoinkyNL** [comment]
Hi, thanks for the update. It seems to be an issue with the Windows Profile, as mentioned in #102.
I'll look into it tonight when I get home

**Comment by medifin** [comment]
It crashes with my g810 aswell.
Thank you for your work. Looks amazing so far.

**Comment by SpoinkyNL** [comment]
Hey, if it still crashes could you try running the following command in a command prompt with Administrator rights:
`lodctr /R`

You can open a command prompt by searching for **cmd** in start and running it as administrator

**Comment by medifin** [comment]
Doesn't crash for me anymore, it just takes a long time to start the app and some actions can take a long time too

**Comment by danii359** [comment]
it fixed for me after the cmd suggestion

**Comment by danii359** [comment]
thanks for the great support dude

**Comment by SpoinkyNL** [comment]
Thanks for reporting back. Automatic that command seems like a bad idea for now. Instead I've made sure Artemis no longer crashes. 

I'll include the command in the FAQ for future reference
