### ISSUE TITLE
Error when trying to enable Windows 10 Default Profile

### ISSUE THREAD

**Issue by pt-r** [SpoinkyNL/Artemis#102]
This is the error message i got

```
An unexpected error occurred in Artemis.

Exception has been thrown by the target of an invocation.

Cannot load Counter Name data because an invalid index '' was read from the registry.
____________________________________________________
System.Reflection.TargetInvocationException

Message:
Exception has been thrown by the target of an invocation.

Stack Trace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Caliburn.Micro.ActionMessage.<>c.<.cctor>b__33_0(ActionExecutionContext context)
   at Caliburn.Micro.ActionMessage.Invoke(Object eventArgs)
   at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

Source:
mscorlib

HResult:
-2146232828
____________________________________________________
System.InvalidOperationException

Message:
Cannot load Counter Name data because an invalid index '' was read from the registry.

Stack Trace:
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName)
   at Artemis.Modules.Effects.WindowsProfile.WindowsProfileModel.GetPerformanceCounters()
   at Artemis.Modules.Effects.WindowsProfile.WindowsProfileModel.SetupCpu()
   at Artemis.Modules.Effects.WindowsProfile.WindowsProfileModel.Enable()
   at Artemis.Managers.EffectManager.ChangeEffect(EffectModel effectModel, LoopManager loopManager)
   at Artemis.ViewModels.Abstract.EffectViewModel.ToggleEffect()

TargetSite:
System.Collections.Hashtable GetStringTable(Boolean)

Source:
System

HResult:
-2146233079

```

**Comment by SpoinkyNL** [comment]
Hi, this seems to be the same error occuring as #101.

I'll look into it when I get home tonight, thanks for the report :+1:

**Comment by pt-r** [comment]
No worries and thanks for the quick reply!

Lemme know if i can provide any more information

**Comment by SpoinkyNL** [comment]
Hey, could you try running the following command in a command prompt with Administrator rights:
`lodctr /R`

You can open a command prompt by searching for **cmd** in start and running it as administrator.
Please let me know how this works for you so I can automate the fix inside Artemis :)

**Comment by SpoinkyNL** [comment]
I've also updated Artemis to no longer crash when this occurs. 
Without running the command the CPU usage layers won't work, but at least you can use the rest of the program :)

**Comment by pt-r** [comment]
Thanks heaps! I'll test it out

**Comment by SpoinkyNL** [comment]
Hi, is this working well now?
