### ISSUE TITLE
Razer Blackwidow chroma Exception

### ISSUE THREAD

**Issue by FireFlyForLife** [SpoinkyNL/Artemis#107]
I downloaded the release and that didn't go flawlessly so I cloned the project and build it myself with a debugger attached, turns out when I go to the game tab and then to rocket league and then back to the welcome screen my keyboards animation freezes, then when I go back to the game tab in the CanEnable method from BlackWidow,
var blackWidowFound = Chroma.Instance.Query(Devices.Blackwidow).Connected;`
throws an exception:
```
Corale.Colore.Razer.NativeCallException was unhandled by user code
  Function=QueryDevice
  HResult=-2146233088
  Message=Call to native Chroma SDK function QueryDevice failed with error: Unknown: Unknown. (5023)
  Source=Corale.Colore
  StackTrace:
       at Corale.Colore.Core.NativeWrapper.QueryDevice(Guid id)
       at Corale.Colore.Core.Chroma.Query(Guid deviceId)
       at Artemis.DeviceProviders.Razer.BlackWidow.CanEnable() in C:\Users\Maiko\Source\Repos\Artemis\Artemis\Artemis\DeviceProviders\Razer\BlackWidow.cs:line 32
       at Artemis.Managers.DeviceManager.EnableKeyboard(KeyboardProvider keyboardProvider) in C:\Users\Maiko\Source\Repos\Artemis\Artemis\Artemis\Managers\DeviceManager.cs:line 98
       at Artemis.Managers.DeviceManager.EnableLastKeyboard() in C:\Users\Maiko\Source\Repos\Artemis\Artemis\Artemis\Managers\DeviceManager.cs:line 60
       at Artemis.Managers.EffectManager.ChangeEffect(EffectModel effectModel, LoopManager loopManager) in C:\Users\Maiko\Source\Repos\Artemis\Artemis\Artemis\Managers\EffectManager.cs:line 94
       at Artemis.Managers.ProfileManager.SetupProfilePreview(Object sender, ElapsedEventArgs e) in C:\Users\Maiko\Source\Repos\Artemis\Artemis\Artemis\Managers\ProfileManager.cs:line 67
       at System.Timers.Timer.MyTimerCallback(Object state)
  InnerException: 
       ErrorCode=-2147467259
       HResult=-2147467259
       Message=The group or resource is not in the correct state to perform the requested operation
       NativeErrorCode=5023
       InnerException: 
```

Let me know what more info I can give

**Comment by SpoinkyNL** [comment]
Hi, the Razer SDK gives an unknown error, that's not a lot to go on :(

Could you verify that you have SDK access enabled in Synapse, and perhaps update your drivers?

**Comment by FireFlyForLife** [comment]
Yes, indeed when I go to the rocket league layer creator it previewes perfectly fine :/

**Comment by FireFlyForLife** [comment]
Okay so apperently this only happens in if I compile in debug mode...

**Comment by SpoinkyNL** [comment]
Oh that's odd. I can't really test it since I don't have a Chroma. The people I had try Artemis out that do own it didn't report this problem though. Does the latest release work for you now?

**Comment by FireFlyForLife** [comment]
Will try that tomorrow, and edit the postwith the results!

**Comment by FireFlyForLife** [comment]
Can confirm everything works again! :D Even the cs go stuff works now, great job on the program!

**Comment by SpoinkyNL** [comment]
Great, thanks for reporting back 👍
