### ISSUE TITLE
Bug report for ETS 2

### ISSUE THREAD

**Issue by mohsin-mulla** [SpoinkyNL/Artemis#145]
Hello!

As per my reply in the other thread, here's a list of issues I've found with the new ETS 2 profile.

1. Selecting the 64-bit folder location for the game causes the directory link to be truncated to `C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin`, then attempting to change the directory again causes Artemis to crash with the following exception message.

````
System.Exception

Message:
No target found for method PlaceConfigFile.

Stack Trace:
   at Caliburn.Micro.ActionMessage.Invoke(Object eventArgs)
   at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.TextBoxBase.OnLostFocus(RoutedEventArgs e)
   at System.Windows.UIElement.IsFocused_Changed(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.Controls.TextBox.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.ClearValueCommon(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata)
   at System.Windows.DependencyObject.ClearValue(DependencyPropertyKey key)
   at System.Windows.Input.FocusManager.OnFocusedElementChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.Input.FocusManager.SetFocusedElement(DependencyObject element, IInputElement value)
   at System.Windows.Input.KeyboardNavigation.UpdateFocusedElement(DependencyObject focusTarget)
   at System.Windows.FrameworkElement.OnGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.UIElement.Focus()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
Void Invoke(System.Object)

Source:
Caliburn.Micro.Platform

HResult:
-2146233088
```


2. Adding a light layer for the F3 key does not light up the key, adding a light layer for the F4 key highlights both the F3 and F4 keys. This is using a Corsair Strafe RGB keyboard.

3. The `Lights - Beacon` condition always seems to keep the lights on regardless of whether the beacon flag is set to true or false. I've verified this using the SDK demo with the game running in the background.

4. The profile seemed to work for a short while before it stopped working altogether. The logfile shows this.

```
2016-08-26 00:58:13.1220|INFO|Artemis.Managers.MainManager|Detected and enabling game: EurotruckSimulator2 
2016-08-26 00:59:14.2290|INFO|Artemis.Utilities.DataReaders.PipeServer|Closed named pipe 'artemis' 
2016-08-26 00:59:14.2890|FATAL|Artemis.App|Unhandled exception, showing dialog and shutting down. System.NullReferenceException: Object reference not set to an instance of an object.
   at Artemis.Modules.Games.EurotruckSimulator2.EurotruckSimulator2Model.Dispose()
   at Artemis.Managers.MainManager.Dispose()
   at Ninject.Activation.InstanceReference.IfInstanceIs[T](Action`1 action)
   at Ninject.Infrastructure.Language.ExtensionsForIEnumerableOfT.Map[T](IEnumerable`1 series, Action`1 action)
   at Ninject.Activation.Pipeline.Deactivate(IContext context, InstanceReference reference)
   at Ninject.Activation.Caching.Cache.Forget(IEnumerable`1 cacheEntries)
   at Ninject.Activation.Caching.Cache.Clear()
   at Ninject.KernelBase.Dispose(Boolean disposing)
   at Artemis.ArtemisBootstrapper.OnExit(Object sender, EventArgs e)
   at System.Windows.ExitEventHandler.Invoke(Object sender, ExitEventArgs e)
   at System.Windows.Application.OnExit(ExitEventArgs e)
   at Artemis.App.OnExit(ExitEventArgs e)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2016-08-26 00:59:14.3120|FATAL|Artemis.App|Unhandled exception, showing dialog and shutting down. System.InvalidOperationException: The Application object is being shut down.
   at System.Windows.Application.GetResourcePackage(Uri packageUri)
   at System.Windows.Application.GetResourceOrContentPart(Uri uri)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at WpfExceptionViewer.ExceptionViewer..ctor(String headerMessage, Exception e, Window owner)
   at Artemis.App.GetArtemisExceptionViewer(Exception e)
   at Artemis.App.Application_DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e)
   at System.Windows.Threading.DispatcherUnhandledExceptionEventHandler.Invoke(Object sender, DispatcherUnhandledExceptionEventArgs e)
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2016-08-26 00:59:21.1710|FATAL|Artemis.Utilities.Logging|INFO: Set log level to Info 
2016-08-26 00:59:21.5539|INFO|Artemis.Managers.DeviceManager|Intialized DeviceManager with 7 device providers 
2016-08-26 00:59:21.5579|INFO|Artemis.Managers.EffectManager|Intialized EffectManager 
2016-08-26 00:59:21.5579|INFO|Artemis.Managers.LoopManager|Intialized LoopManager 
2016-08-26 00:59:21.5579|INFO|Artemis.Managers.ProfileManager|Intialized ProfileManager 
2016-08-26 00:59:21.5894|INFO|Artemis.Utilities.DataReaders.PipeServer|Opened named pipe 'artemis' 
2016-08-26 00:59:21.5894|INFO|Artemis.Managers.MainManager|Intialized MainManager 
2016-08-26 00:59:21.5894|INFO|Artemis.Managers.MainManager|Artemis version 1.3.0.0 is ready! 
2016-08-26 00:59:21.6044|INFO|Artemis.Utilities.Updater|Update check enabled: True 
2016-08-26 00:59:23.3915|INFO|Artemis.Utilities.Updater|Update check complete 
2016-08-26 00:59:26.6326|INFO|Artemis.Managers.MainManager|Detected and enabling game: EurotruckSimulator2 
2016-08-26 00:59:26.6706|FATAL|Artemis.Utilities.Logging|INFO: Set log level to Info 
2016-08-26 00:59:27.6294|INFO|Artemis.Managers.MainManager|Detected and enabling game: EurotruckSimulator2 
2016-08-26 00:59:27.6909|FATAL|Artemis.Utilities.Logging|INFO: Set log level to Info 
2016-08-26 01:00:22.0306|INFO|Artemis.Managers.MainManager|Disabling game: EurotruckSimulator2 
2016-08-26 01:00:22.0506|FATAL|Artemis.Utilities.Logging|INFO: Set log level to Info 
```

I have yet to restart my computer in case something's gone awry (got some open stuff I need to work on before I can restart...), but I will report back if the problem persists after a restart.

There's a few small feature requests I'd like to make as well, but I think I'll put that in a separate issue :)

**Comment by SpoinkyNL** [comment]
Hey, I forgot that the full game is 64-bit, the demo is just 32-bit.
Could you confirm for me that the 64-bit .exe is also just called eurotrucks2.exe?

#### Point 1 
This isn't something I can fix very easily, since the keys aren't a perfect grid sometimes a pixel gets spread across two to keep the image from becoming distorted
#### Point 2 
Do you mean that the data is inaccurate on both the SDK demo and Artemis? I've already had to modify the code used in the demo a bit so I think I could fix this too
#### Point 3 
I think I have a fix for this already, did this crash occur when you closed the game?

**Comment by mohsin-mulla** [comment]
Hehe yeah, I was confused as to why it wasn't working at all first, then I realised the SDK wasn't installed.

I can confirm that the 64-bit .exe is also called eurotrucks2.exe.

1. I see what you mean, I guess it's not a major issue, maybe a fix for a future release...?

2. The SDK demo reports the correct value for when the beacons are on which = True, however, Artemis seems to active the beacon light layer regardless of whether the value is True or False.

3. Artemis crashed when I closed it with the game open, as I was trying to see whether I could get Artemis to reload the profile but to no avail. I've restarted my system as well and the lights still don't change.

**Comment by SpoinkyNL** [comment]
Alright thanks for the reply, I've pushed an update which you should have when you restart Artemis, let me know how it goes with that version

**Comment by mohsin-mulla** [comment]
Excellent! Just got the auto-update and did some further testing :)

So I noticed Artemis automatically selected the 64-bit directory of the game which is good. To test the previous issue further (and your new fix!), I selected the 32-bit directory of the game. In doing so, I received an error message telling me to select a valid directory, and the path had been changed to `C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin`.

Other issues I've picked up include (sorry if some of these seem nit picky): 

1. Animations don't seem to work for some of the conditions available. For example, `BlinkerLeftOn` works properly, with the light layer flashing as expected with the corresponding animation speed value.  But if you try `LightsBeaconOn`, or `Paused`, the light layer does not flash in-game. Another example I tried was getting the RPM light layer to flash at max RPM like a real vehicle does, but that didn't seem to work either. There may be others with this issue that I have not tested.

2. Some conditions seem to be calculating incorrectly? E.g. I have a light layer for the fuel on the number pad, with a height of `Truck -> Fuel` % property of `Truck -> FuelCapacity`. The value for `Fuel` was 780.445557 and `FuelCapacity` was 1135.0, yet the light layer was showing there was only 1/4 of fuel left.

You can also see this with the `UserThrottle` values. Applying half throttle (so 0.5) and none of the lights were lit up, until you apply about 75% throttle which is when you see the light layer working. Brake lights also have a similar issue.

3. This is unrelated to the bug report, but I'm struggling to understand how the "Is Event" feature is supposed to work. I tried creating an event where by when `Engine = True`, a light layer is shown for 2 seconds before disappearing but it didn't seem to work.

4. Once this is all fixed up, could you look into adding American Truck Simulator as a game option? It uses the exact same SDK with the exact same variables. It should be as simple as adding a new game option and using the same options as you did in ETS 2.

I'm attaching my profile so you can troubleshoot further :)

Thanks for all the work you've done so far, you are a true gentleman!

[ETS2.zip](https://github.com/SpoinkyNL/Artemis/files/440921/ETS2.zip)

**Comment by SpoinkyNL** [comment]
Thanks for the feedback and profile, some things are hard to test for me because my demo truck doesn't even have a beacon light (or at least nothing happened ingame when I turned it on) Nothing is too nitpicky, everything should work afterall :+1: 

I'll go by your stuff point-for-point to keep it readable

1. The reason the layers for BlinkerLeftOn and BlinkerRightOn are blinking in sync with the game is because the SDK actually sets the lights to on and off, so Artemis picks that up as well. If you'd like layers to blink you can apply the pulse animation to the layers and they'll blink/pulse as well, however you may have to adjust the animation speed to get them somewhat in sync with the game. I'll include a profile for ETS 2 in the next update where I've got some animations going.

2. Looks like there are some rounding issues with decimal values, I'll definitely get those sorted, that should fix point 2.

3. The event feature isn't ready yet, I probably should've taken the switch out to avoid confusion, sorry about that one. But the way you tried to use it is how it's supposed to work when it's done :)

4. I'll add support for ATS as well when this is ironed out, shouldn't be much more trouble

For your scenario of showing a flashing layer when you're on max RPM I would have to add some new functionality to the conditions system (my trucks engine would't go past 2420 RPM where the max was 2500). 

 Right now you can show a layer with a condition like so :
```Truck -> EngineRpm -> Greater or equal to '2420'```
But since every truck is different we would need:
```Truck -> EngineRpm -> Greater or equal to '90% of EngineMaxRpm'```

That brings quite a lot of extra variables to the table, and it's something I wanted to provide with #121 

To make sure I get all the folder and stuff right, could you provide screenshots of the 64-bit and 32-bit directory of both ETS2 and ATS?

Thanks again for your feedback, this one has been fun for me so far!

**Comment by mohsin-mulla** [comment]
No worries, that's awesome! :smile:  Haha, I can see why beacons aren't working for you... you have to install it on your truck using a service garage paying for it with in-game currency. I will attach a completed save profile which I found online with "cheated" in money and a truck with all the additional lights installed :)
[Euro Truck Simulator 2.zip](https://github.com/SpoinkyNL/Artemis/files/441211/Euro.Truck.Simulator.2.zip)

I've attached a screenshot from WinDirStat of the American Truck Simulator folder showing all the sub-directories and files within directories. You might notice there's no 32-bit executable; a 32-bit version does exist. However, the developers do not plan to support it for much longer, so maybe it's not worth adding 32-bit support with this considered. (You can read more [here](http://blog.scssoft.com/2016/02/american-truck-simulator-release.html) if you're interested)

![windirstat_2016-08-28_16-55-36](https://cloud.githubusercontent.com/assets/7242533/18034887/e0e4f054-6d40-11e6-9b94-594b53c4d46c.png)

The trucks max RPM is an interesting one, since you are right, each truck will generally have a different max RPM depending on the manufacturer and engine. It's not a huge deal, but it'd be nice to have

I'll have to keep my eyes peeled for the "Is event" feature then :) and I'm glad you're having fun working on this, it feels nice to be a part of the development process somewhat haha

**Comment by SpoinkyNL** [comment]
Hey, this should work quite well I'll close this issue and open a new one that's only about adding American Truck Simulator
