### ISSUE TITLE
I get this error message when trying to install or use the program

### ISSUE THREAD

**Issue by Praxis459** [SpoinkyNL/Artemis#183]
An unexpected error occurred in Artemis.

Exception has been thrown by the target of an invocation.

Exception has been thrown by the target of an invocation.

Object reference not set to an instance of an object.

---

System.Reflection.TargetInvocationException

Message:
Exception has been thrown by the target of an invocation.

Stack Trace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ninject.Infrastructure.Language.ExtensionsForIEnumerable.ToArraySlow(IEnumerable series, Type elementType)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Artemis.ArtemisBootstrapper.GetInstance(Type service, String key)
   at Caliburn.Micro.BootstrapperBase.DisplayRootViewFor(Type viewModelType, IDictionary`2 settings)
   at Artemis.ArtemisBootstrapper.OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

Source:
mscorlib

HResult:
-2146232828

---

System.Reflection.TargetInvocationException

Message:
Exception has been thrown by the target of an invocation.

Stack Trace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ninject.Infrastructure.Language.ExtensionsForIEnumerable.ToArraySlow(IEnumerable series, Type elementType)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)

TargetSite:
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

Source:
mscorlib

HResult:
-2146232828

---

System.NullReferenceException

Message:
Object reference not set to an instance of an object.

Stack Trace:
   at Artemis.DAL.ProfileProvider.ReadProfiles()
   at Artemis.DAL.ProfileProvider.GetAll()
   at Artemis.Modules.Games.UnrealTournament.UnrealTournamentViewModel.InstallGif()
   at DynamicInjector39c68454ace14ef0a1e7b1b5b3b7d03d(Object[] )
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)

TargetSite:
Void ReadProfiles()

Source:
Artemis

HResult:
-2147467261

**Comment by SpoinkyNL** [comment]
Hi, that's unfortunate :(

The error seems to be related to the installation of the default profiles. If you head to Documents is there a folder called Artemis with a subfolder called profiles there?
`Documents > Artemis > profiles`

**Comment by Praxis459** [comment]
Yes there is,  all the folders under there have something in them.

**Comment by SpoinkyNL** [comment]
Ok, could you remove the entire Artemis folder and try again? I see a possible null reference exception when it fails to load a profile so removing them all might fix it

**Comment by Praxis459** [comment]
I get this error when I remove the folder: An unexpected error occurred in Artemis.

Exception has been thrown by the target of an invocation.

Exception has been thrown by the target of an invocation.

Object reference not set to an instance of an object.
____________________________________________________
System.Reflection.TargetInvocationException

Message:
Exception has been thrown by the target of an invocation.

Stack Trace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ninject.Infrastructure.Language.ExtensionsForIEnumerable.ToArraySlow(IEnumerable series, Type elementType)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Artemis.ArtemisBootstrapper.GetInstance(Type service, String key)
   at Caliburn.Micro.BootstrapperBase.DisplayRootViewFor(Type viewModelType, IDictionary`2 settings)
   at Artemis.ArtemisBootstrapper.OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

Source:
mscorlib

HResult:
-2146232828
____________________________________________________
System.Reflection.TargetInvocationException

Message:
Exception has been thrown by the target of an invocation.

Stack Trace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ninject.Infrastructure.Language.ExtensionsForIEnumerable.ToArraySlow(IEnumerable series, Type elementType)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)

TargetSite:
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

Source:
mscorlib

HResult:
-2146232828
____________________________________________________
System.NullReferenceException

Message:
Object reference not set to an instance of an object.

Stack Trace:
   at Artemis.DAL.ProfileProvider.ReadProfiles()
   at Artemis.DAL.ProfileProvider.GetAll()
   at Artemis.Modules.Games.UnrealTournament.UnrealTournamentViewModel.InstallGif()
   at DynamicInjector39c15279f6e342a2a136270332ce6631(Object[] )
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)

TargetSite:
Void ReadProfiles()

Source:
Artemis

HResult:
-2147467261

**Comment by SpoinkyNL** [comment]
Hmm, alright. Could you try it with this version? https://www.dropbox.com/s/tuqxojl816s01tj/possible-null-reference-fix.zip?dl=0

Just extract it, run Artemis.exe and see how it goes.

Thanks!

**Comment by SpoinkyNL** [comment]
Had a bit of trouble compiling a working porable version, but could you give this a shot?
https://www.dropbox.com/s/gytb0c1z7t4gn73/possible-fix.zip?dl=0

Make sure you get all the files and just go into `extract the whole folder >Release > Artemis.exe`

**Comment by Praxis459** [comment]
So the test version worked up until I trie dto use a Gif.  But it launches now and I am able to apply some effects to the keyboard.  I haven't tried the mouse or headset yet.

**Comment by SpoinkyNL** [comment]
Ok that's one step closer. GIFs should be working though.

Could you pass me the log in `Documents > Artemis > logs` and the error you get when you try a GIF?

**Comment by Praxis459** [comment]
[2016-10-25.2.txt](https://github.com/SpoinkyNL/Artemis/files/551165/2016-10-25.2.txt)

**Comment by SpoinkyNL** [comment]
From what I can tell the crash is related to audio capture, which is used in some layers.
Does your PC have any audio related software running? From what I can tell MSI's Nahimic software can cause this crash

**Comment by Praxis459** [comment]
No not really, I have the logitech software running, then Discord, and Google hangouts and the standard realtek audio drivers.  And Sonic Suite 2 but it doesn't do anything as far as I Can tell.

**Comment by SpoinkyNL** [comment]
Alright, since it's an error caused by a library I'm using, I'll make sure Artemis won't crash when it happens in the next update

That'll means audio visualization layers sadly won't work for you but atleast you'll be able to use the rest of the program without any issues

**Comment by Praxis459** [comment]
Ok thank you for all the hard work you do on this program :) I only
typically use the volume overlay on it to see what volume my system is at.
Thank you again,
Blake
