### ISSUE TITLE
Crash when loading any of the MasterKeys profiles

### ISSUE THREAD

**Issue by yokuyuki** [SpoinkyNL/Artemis#220]
Regardless of which MasterKeys profile I select (I have a MasterKeys S), it just crashes as soon as I select it. Below is the crash log.

```
System.BadImageFormatException

Message:
An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

Stack Trace:
   at Artemis.DeviceProviders.CoolerMaster.Utilities.CmSdk.SetControlDevice(DEVICE_INDEX devIndex)
   at Artemis.DeviceProviders.CoolerMaster.MasterkeysProS.CanEnable()
   at Artemis.DeviceProviders.KeyboardProvider.<>c__DisplayClass31_0.<CanEnableAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Artemis.Managers.DeviceManager.<EnableKeyboard>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
Void SetControlDevice(Artemis.DeviceProviders.CoolerMaster.Utilities.DEVICE_INDEX)

Source:
Artemis

HResult:
-2147024885
```

**Comment by maddtom1** [comment]
Having the same exact issue with my Logitech G910 RGB. Whenever I attempt to select the profile in settings Artemis crashes with the same error as _yokuyuki_

'An attempt was made to load a program with an incorrect format.'

**Comment by SpoinkyNL** [comment]
Hey thanks for the log, I made a mistake and compiled the new update in the wrong way :\

[This version](https://github.com/SpoinkyNL/Artemis/releases/download/1.6.0.1/Setup.exe) should work just fine for you, sorry for the inconvenience!

**Comment by yeungmoney** [comment]
Had the same exact problem! I'll try this tonight

**Comment by yokuyuki** [comment]
Problem fixed.
