### ISSUE TITLE
Generic device lights dont seem to work straight away when starting up. Also random crashes sometimes

### ISSUE THREAD

**Issue by Arttumiro** [SpoinkyNL/Artemis#224]
When my mouse lights don't work i gotta change the mouse lights to any other category and back to make it work.

here is what the Exeption says when it crashes:
An unexpected error occurred in Artemis.

Collection was modified; enumeration operation may not execute.
____________________________________________________
System.InvalidOperationException

Message:
Collection was modified; enumeration operation may not execute.

Stack Trace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Artemis.Profiles.Layers.Types.KeyPress.KeyPressType.Update(LayerModel layerModel, IDataModel dataModel, Boolean isPreview)
   at Artemis.Profiles.Layers.Models.LayerModel.Update(IDataModel dataModel, Boolean preview, Boolean updateAnimations)
   at Artemis.Profiles.ProfileModel.DrawLayers(Graphics g, IEnumerable`1 renderLayers, IDataModel dataModel, Rect rect, Boolean preview, Boolean updateAnimations, String updateType)
   at Artemis.Models.EffectModel.Render(RenderFrame frame, Boolean keyboardOnly)
   at Artemis.Managers.LoopManager.Render()
   at Artemis.Managers.LoopManager.LoopTimerOnElapsed(Object sender, ElapsedEventArgs elapsedEventArgs)

TargetSite:
Void ThrowInvalidOperationException(System.ExceptionResource)

Source:
mscorlib

HResult:
-2146233079

Edit: only crashes if i hold or press many buttons at once and i have a keypress effect.

**Comment by SpoinkyNL** [comment]
Hey, will look into both issues, the stacktrace helps a lot thanks

**Comment by SpoinkyNL** [comment]
Hey, I've pushed an update that resolves this. If you restart Artemis it'll auto-update, restart again to launch the new version.

Should you still have any issues, don't hesitate to open a new thread :)
