### ISSUE TITLE
The blinking is back. (Relaunching fixed it) Edit: came back

### ISSUE THREAD

**Issue by Arttumiro** [SpoinkyNL/Artemis#233]
Just after i installed the nvidia drivers the mouse lights decided to break again. Also it shows up on your debugger thingy.
Edit: Relaunching fixed it.
Edit n.2: came back for no reason

**Comment by SpoinkyNL** [comment]
Hey,

Does it also blink in the preview or only on the mouse itself?

**Comment by Arttumiro** [comment]
It blinks in the preview too.

**Comment by Arttumiro** [comment]
Now my keypress effects are buggy too. they blink just like the mouse lights. Also show up on the preview

**Comment by SpoinkyNL** [comment]
Alright, weird stuff. Could you send me your profile that you're using?

**Comment by Arttumiro** [comment]
[Artemis Lighting effects.zip](https://github.com/SpoinkyNL/Artemis/files/657209/Artemis.Lighting.effects.zip)

**Comment by SpoinkyNL** [comment]
I noticed you have the display bound to scroll-lock on many layers, perhaps that's buggin on your system?
Try taking off that condition, it's on the Mouse Rainbow layer and the ripple effects

**Comment by Arttumiro** [comment]
The ripple effects are on numlock and the mouse effect is on scroll lock. And it was working on the last version

**Comment by SpoinkyNL** [comment]
I understand, but does taking them off solve the blinking issue?

**Comment by Arttumiro** [comment]
Yea it fixed the keyboard ones. But when adding the mouse bind back the software crashed with this error:
An unexpected error occurred in Artemis.

Collection was modified; enumeration operation may not execute.
____________________________________________________
System.InvalidOperationException

Message:
Collection was modified; enumeration operation may not execute.

Stack Trace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Artemis.Profiles.Layers.Conditions.DataModelCondition.ConditionsMet(LayerModel layerModel, IDataModel dataModel)
   at Artemis.Profiles.Layers.Models.LayerModel.GetRenderLayers(IDataModel dataModel, Boolean keyboardOnly, Boolean ignoreConditions)
   at Artemis.Profiles.ProfileModel.GetRenderLayers(IDataModel dataModel, Boolean keyboardOnly, Boolean ignoreConditions)
   at Artemis.Models.EffectModel.Render(RenderFrame frame, Boolean keyboardOnly)
   at Artemis.Managers.LoopManager.Render()
   at Artemis.Managers.LoopManager.LoopTimerOnElapsed(Object sender, ElapsedEventArgs elapsedEventArgs)

TargetSite:
Void ThrowInvalidOperationException(System.ExceptionResource)

Source:
mscorlib

HResult:
-2146233079

**Comment by Arttumiro** [comment]
Everything is working now after restarting and adding the keybinds.

**Comment by SpoinkyNL** [comment]
Great! Thanks for your patience
