### ISSUE TITLE
Can you take a closer look at this error?

### ISSUE THREAD

**Issue by Arttumiro** [SpoinkyNL/Artemis#236]
An unexpected error occurred in Artemis.

Collection was modified; enumeration operation may not execute.
____________________________________________________
System.InvalidOperationException

Message:
Collection was modified; enumeration operation may not execute.

Stack Trace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Artemis.Profiles.Layers.Conditions.DataModelCondition.ConditionsMet(LayerModel layerModel, IDataModel dataModel)
   at Artemis.Profiles.Layers.Models.LayerModel.GetRenderLayers(IDataModel dataModel, Boolean keyboardOnly, Boolean ignoreConditions)
   at Artemis.Profiles.ProfileModel.GetRenderLayers(IDataModel dataModel, Boolean keyboardOnly, Boolean ignoreConditions)
   at Artemis.Models.EffectModel.Render(RenderFrame frame, Boolean keyboardOnly)
   at Artemis.Managers.LoopManager.Render()
   at Artemis.Managers.LoopManager.LoopTimerOnElapsed(Object sender, ElapsedEventArgs elapsedEventArgs)

TargetSite:
Void ThrowInvalidOperationException(System.ExceptionResource)

Source:
mscorlib

HResult:
-2146233079

**Comment by SpoinkyNL** [comment]
Hey, I've fixed this and also changed how easily Artemis crashes. If stuff like this happens it's usually because you're editing the profile anyways.

In the next version errors like these will be logged in case it's causing issues but Artemis won't crash.

**Comment by Arttumiro** [comment]
Ok well thanks for the reply.
