### ISSUE TITLE
SDK does not work from CMD

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#317]
If I open Artemis from CMD or batch file, Artemis can not connect to Corsair's API but if I double click on the exe manually then it works just fine. I just compiled from latest development branch and still happening.

PS. I don't to open another issue but I do not have access to your D drive so Artemis crashes when it tries to open D:\Gebruiker folder\Documents\Artemis\gifs\demo-gif.gif

**Comment by SpoinkyNL** [comment]
Hey, thanks for the report, could you give me a stack trace off the crash?
The demo profile needs a GIF file but it shouldn't leave my own folder in there, obviously. 

As for it not working from CMD, it's a bit weird..
It works alright if you run it from the same folder, like this
```cmd
C:\Users\Robert\Desktop\artemis-1820-beta\Release>Artemis.exe
```

But executing it with the full path from somewhere else caused the issue you described
```cmd
C:\>C:\Users\Robert\Desktop\artemis-1820-beta\Release\Artemis.exe
```

However, there's a third option that always seems to work, and that's by running it through the updater (that's how the shortcuts do it and it ensures you're always running the latest version)
```cmd
C:\>C:\Users\Robert\Desktop\artemis-1820-beta\Update.exe --processStart "Artemis.exe"
```

If it's giving you trouble I'll look into it but I recommend running it through the updater as shown in my last example

**Comment by rakosi2** [comment]
I am compiling the development branch. The updater is in folder Artemis\bin\x64 and there is also debug and release folders. When I run the command, it errors. I tried to copy the updater to the debug folder and same result.

2017-03-02 22:36:25> Program: Starting Squirrel Updater: --processStart Artemis.exe
2017-03-02 22:36:26> Unhandled exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Documents\Artemis-development\Artemis\Artemis\bin\x64\Debug\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at Squirrel.Update.Program.ProcessStart(String exeName, String arguments, Boolean shouldWait)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

I created a batch file that cd's into the directory and then runs the start command for task scheduler and that temporarily fixed the issue.

**Comment by SpoinkyNL** [comment]
I got rid of Squirrel (the auto-updater) so it should be fine now.

However, I noticed that Artemis (and more precisely CUE.NET) doesn't like being started from a different working directory then where Artemis.exe is located.

So if you're running Artemis from a cmd, please do the following:
```bat
cd "C:\Program Files\Artemis"
start "Artemis.exe"
```
(Assuming that's where you've installed it ofcourse)

_I see you were already doing this, just writing it down for reference though_

**Comment by rakosi2** [comment]
I was keeping this batch script in the Artemis folder in the Documents but I just noticed that Artemis is moving everything from Documents to C:\ProgramData\Artemis
