### ISSUE TITLE
Bubbles not working?

### ISSUE THREAD

**Issue by Praxis459** [SpoinkyNL/Artemis#323]
Hi I keep recieving this message in the log files and the application won't display the Bubbles plugin on my keyboard.
2017-03-13 09:51:58.7563|WARN|Artemis.Managers.LoopManager|Exception in render loop System.ArgumentNullException: Value cannot be null.
Parameter name: image
   at System.Drawing.Graphics.FromImage(Image image)
   at Artemis.Modules.General.Bubbles.BubblesModel.Render(FrameModel frameModel, Boolean keyboardOnly) in C:\Repos\Artemis\Artemis\Artemis\Modules\General\Bubbles\BubblesModel.cs:line 96
   at Artemis.Managers.LoopManager.Render() in C:\Repos\Artemis\Artemis\Artemis\Managers\LoopManager.cs:line 168
   at Artemis.Managers.LoopManager.ProcessLoop() in C:\Repos\Artemis\Artemis\Artemis\Managers\LoopManager.cs:line 59

**Comment by SpoinkyNL** [comment]
Hi, thanks for the report I'll look into it.

PS: Is this a version you built yourself?

**Comment by Praxis459** [comment]
Nope its just an update 1.8.1.0 I updated from a really old version 1.0.4.1
I think.

**Comment by SpoinkyNL** [comment]
Found the issue, I'll fix it for the next release :)

**Comment by Praxis459** [comment]
Ok thanks :)

**Comment by SpoinkyNL** [comment]
Fixed in the latest release

**Comment by Praxis459** [comment]
Thanks :)
