### ISSUE TITLE
[Win 7] Artemis not detecting my keyboard (Razer BW Chroma)

### ISSUE THREAD

**Issue by jensenhuangyankai** [SpoinkyNL/Artemis#337]
Log:
```
System.NullReferenceException

Message:
Object reference not set to an instance of an object.

Stack Trace:
   at WpfExceptionViewer.ExceptionViewer.AddProperty(List`1 inlines, String propName, Object propVal)
   at WpfExceptionViewer.ExceptionViewer.AddException(Exception e)
   at WpfExceptionViewer.ExceptionViewer.BuildTree(Exception e, String summaryMessage)
   at Artemis.App.GetArtemisExceptionViewer(Exception e)
   at Artemis.App.Application_DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e)
   at System.Windows.Threading.DispatcherUnhandledExceptionEventHandler.Invoke(Object sender, DispatcherUnhandledExceptionEventArgs e)
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
Void AddProperty(System.Collections.Generic.List`1[System.Windows.Documents.Inline], System.String, System.Object)

Source:
VioletTape.WpfExceptionViewer

HResult:
-2147467261

An unexpected error occurred in Artemis.

Object reference not set to an instance of an object.
```

**Comment by SpoinkyNL** [comment]
Hey, I'll hopefully have time to look into this during the weekend, in the meanwhile could you do the following for me?

1. Open up the settings menu and set the loggin level to ```debug```.
2. Set the keyboard to Razer, which will cause a crash again
3. Head into ```Documents > Artemis > logs```.
4. Drag the ```log.txt``` file into the GitHub comment box, uploading it.
5. Optionally set the logging back to Info to keep your log files small.

Thanks!

**Comment by jensenhuangyankai** [comment]
it seems that the bug is caused by artemis trying to re-enable the keyboard after already enabling it

**Comment by abjugard** [comment]
I'm getting this as well, same keyboard. Artemis crashes as soon as it gets focus again after having lost focus.

Steps to reproduce:

1. Open Artemis, select Razer BlackWidow Chroma keyboard
2. Go to Games, select a game
3. Change focus to some other application
4. Focus Artemis again
5. Artemis shows "Trying to enable keyboard: Razer BlackWidow Chroma"
6. Artemis crashes

Here is a [log](https://github.com/SpoinkyNL/Artemis/files/893741/log.txt) with logging level set to trace.

Artemis has always done this for me, its actually never worked at all.

**Comment by SpoinkyNL** [comment]
Hey, please try this release:
https://github.com/SpoinkyNL/Artemis/releases/tag/1.9.0.2

Just grab the Setup.exe and please let me know how it goes :)
